services:
  # postgres:
  #   image: postgres
  #   hostname: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_DB: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - pg-data:/var/lib/postgresql/data
  #   ports:
  #     - "5433:5432"
  #   networks:
  #     - mynetwork
  workhunter.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - 55431:8080
      - 55432:8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
      - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro
    networks:
      - mynetwork
volumes:
    pg-data:
networks:
  mynetwork:
     driver: nat
     driver_opts:
       com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
       # com.docker.network: "default"