services:
  postgres:
    image: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: whunter
      POSTGRES_USER: whunter
      POSTGRES_PASSWORD: tva8g,-c_d19bn8*
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  workhunter.api:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_HTTPS_PORTS: 8081
      ConnectionStringWHunter: "Server=localhost;Port=5432;Database=whunter;User Id=whunter;Password=\"tva8g,-c_d19bn8*\"" 
    ports:
      - 55431:55431
      - 55432:55432
      - 8080:8080
      - 8081:8081
    depends_on:
      - postgres
    # volumes:
      # - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
      # - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro
    networks:
      - mynetwork

volumes:
    pg-data:

networks:
  mynetwork:
     driver: bridge 
     driver_opts:
       com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
       # com.docker.network: "default"