# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PROJECT_API_NAME: WorkHunter.Api
      PROJECT_API_PATH_NAME: WorkHunter.Api
      PROJECT_NAME_TESTS: WorkHunter.UnitTests
      PROJECT_PATH: WorkHunter
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}/${{ env.PROJECT_PATH }}.sln
    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }}/${{ env.PROJECT_API_PATH_NAME }}/${{ env.PROJECT_API_NAME }}.csproj -c Release -o content --no-restore
    - name: Test
      run: dotnet test ${{ env.PROJECT_PATH }}/${{ env.PROJECT_NAME_TESTS }}/${{ env.PROJECT_NAME_TESTS }}.csproj --verbosity normal
